# Use the official Python image as the base image
FROM python:3.7.3-alpine

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY ../requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port that the Flask application will run on
EXPOSE 5000

# Set the entrypoint command to run the Flask application
CMD ["python", "app.py"]