name: Simulate Sensor Data Addition
env:
  AWS_ACCESS_KEY_ID: '${{secrets.AWS_ACCESS_KEY_ID}}'
  AWS_SECRET_ACCESS_KEY: '${{secrets.AWS_SECRET_ACCESS_KEY}}'
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Env Variables
        run: |
        

      # Add your desired steps here
      - name: Install dvc
        run: |
          python -m pip install --upgrade pip
          pip install -U pyopenssl cryptography
          pip install dvc[s3] dvc-s3 pandas
          dvc --version
      - name: Setup DVC
        run: |
          dvc init
          dvc remote add -d aws s3://${{secrets.S3_LINK}}
      - name: Pulling data from dvc
        run: |
          dvc --version
          dvc repro
