name: Manual Workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Install dvc
        run: 'pip install dvc[gdrive]'

      - name: Pulling data from dvc
        run: 'dvc pull'

      - name: Add more data
        run: 'python generate_data.py'

      - name: Push data back to gdrive
        run: 'dvc push -r myremote'
