name: Simulate Sensor Data Addition
env:
  AWS_ACCESS_KEY_ID: '${{secrets.AWS_ACCESS_KEY_ID}}'
  AWS_SECRET_ACCESS_KEY: '${{secrets.AWS_SECRET_ACCESS_KEY}}'
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0,12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      # Add your desired steps here
      - name: Configurations
        run: |
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"

      - name: Install dvc
        run: |
          make install
          dvc --version
      - name: Setup DVC
        run: |
          dvc remote add -d aws s3://${{secrets.S3_LINK}}
      - name: Pulling data from dvc
        run: |
          dvc --version
          dvc repro --force
      - name: Save new files back to github repo
        run: |
          git add dvc.lock data/dummy_sensor_data.csv.dvc
          git commit -m "Update .dvc files after running dvc repro"
          git push origin main
