name: Simulate Sensor Data Addition
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your desired steps here
      - name: Install dvc
        run: |
          pip install -r requirements.txt
          dvc --version

      - name: Pulling data from dvc
        run: |
          dvc --version
          dvc pull -r myremote

      - name: Add more data        
        run: |
          python generate_data.py
          dvc add data/dummy_sensor_data.csv

      - name: Push data back to gdrive
        run: 'dvc push -r myremote'
